# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imup < Formula
  desc "imweb internal toolkit"
  homepage "https://www.imweb.me"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.4/imup_0.1.4_darwin_amd64.tar.gz"
      sha256 "372e1a82ae366bd55d5c78f275400ef6204b922bc6187574dde3bd3700bcf0bf"

      def install
        bin.install "imup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.4/imup_0.1.4_darwin_arm64.tar.gz"
      sha256 "42e87d563d70d89ef0f13ff5569a251ba3a152024a040beafe13558ed0242d99"

      def install
        bin.install "imup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.4/imup_0.1.4_linux_arm64.tar.gz"
      sha256 "61863c260bc9a26091f235340932b1082d2b387d70658cc032cc74b6d2731a95"

      def install
        bin.install "imup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.4/imup_0.1.4_linux_amd64.tar.gz"
      sha256 "2f58ed2eddccf38f8e3c533db259769407516eabb599d6d1d03514076ddcf999"

      def install
        bin.install "imup"
      end
    end
  end
end
