# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imup < Formula
  desc "imweb internal toolkit"
  homepage "https://www.imweb.me"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.6/imup_0.1.6_darwin_amd64.tar.gz"
      sha256 "65c3810809d1e3bb46178b4e61d7e4126e84a0ad3b0c463b4c8f84ba20ddd36a"

      def install
        bin.install "imup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.6/imup_0.1.6_darwin_arm64.tar.gz"
      sha256 "dd1e5680173377c68b5877f514a90a6f4c4cd0d5901663569dc5231341d86889"

      def install
        bin.install "imup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.6/imup_0.1.6_linux_amd64.tar.gz"
      sha256 "72ea3d261317c1824e4ace5339fc6c736b3c3ea547efea15acb231be153038ef"

      def install
        bin.install "imup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imwebme/homebrew-imup/releases/download/v0.1.6/imup_0.1.6_linux_arm64.tar.gz"
      sha256 "b97cdca7ed381b9d3552070cdd1be7ec570d7be64effe407bb9c7a56fc25f0f1"

      def install
        bin.install "imup"
      end
    end
  end
end
